import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API=(import.meta.env.VITE_API_URL||'https://jonathan01476--injury-predict-api.modal.run').replace(/\/$/,'');
const fields=[
 {key:'Player_Age',label:'Player age',unit:'years*',min:18,max:39,step:1,value:28,description:'Age recorded for the player.'},
 {key:'Player_Weight',label:'Player weight',unit:'kg*',min:40.191,max:104.651,step:'any',value:75,description:'Body weight within the dataset range.'},
 {key:'Player_Height',label:'Player height',unit:'cm*',min:145.285,max:207.309,step:'any',value:180,description:'Body height within the dataset range.'},
 {key:'Previous_Injuries',label:'Previous injuries',unit:'binary',min:0,max:1,step:1,value:0,description:'Recorded history: 0 = no, 1 = yes.'},
 {key:'Training_Intensity',label:'Training intensity',unit:'0–1 score',min:0,max:1,step:'any',value:0.5,description:'Normalized training intensity, from 0 to 1.'},
 {key:'Recovery_Time',label:'Recovery time',unit:'dataset units',min:1,max:6,step:1,value:4,description:'Recorded recovery value. Time unit undocumented.'}
];
async function request(path,options={}){
 if(!API)throw new Error('API URL is not configured. Set VITE_API_URL and rebuild the frontend.');
 if(import.meta.env.PROD && (!API.startsWith('https://')||/localhost|127\.0\.0\.1/.test(API)))throw new Error('Production requires a public HTTPS API URL.');
 const response=await fetch(API+path,{...options,signal:AbortSignal.timeout(120000)});
 let data;try{data=await response.json()}catch{throw new Error('The API returned an unreadable response.')}
 if(!response.ok)throw new Error(response.status===422?'Please check the feature values and their allowed ranges.':typeof data.detail==='string'?data.detail:`API request failed (${response.status}).`);
 return data;
}
function App(){
 const [values,setValues]=useState(Object.fromEntries(fields.map(f=>[f.key,f.value])));
 const [status,setStatus]=useState('checking'),[metadata,setMetadata]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;const check=async()=>{try{const h=await request('/health');if(active)setStatus(h.model_loaded?'online':'offline');const m=await request('/pipeline');if(active)setMetadata(m)}catch{if(active)setStatus('offline')}};check();const timer=setInterval(check,60000);return()=>{active=false;clearInterval(timer)}},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');setResult(null);try{const data=await request('/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fields.map(f=>[f.key,Number(values[f.key])])))});if(![0,1].includes(data.prediction)||!Number.isFinite(data.injury_probability)||data.injury_probability<0||data.injury_probability>1)throw new Error('The API response does not match the model contract.');setResult(data)}catch(err){setError(err.name==='TimeoutError'?'The model request timed out. Please retry.':err.message)}finally{setBusy(false)}}
 const percent=result?result.injury_probability*100:0;
 return <div className="shell"><div className="ambient"/><header><a className="brand" href="#"><span className="logo">✳</span> INJURY<span>PREDICT</span><small>RESEARCH SYSTEM / 01</small></a><div className={'status '+status}><i/>{status==='online'?'MODEL ONLINE':status==='checking'?'CONNECTING':'MODEL OFFLINE'}</div></header>
 <main><div className="eyebrow"><span/> HUMAN PERFORMANCE INTELLIGENCE <b>ML LAB · V1.0</b></div><section className="hero"><div><h1>Understand the signal.<br/><em>Analyze injury likelihood.</em></h1><p>A real machine-learning pipeline. Six player characteristics.<br/>Explore the injury label predicted from a 1,000-record dataset.</p><div className="tags"><span>SCIKIT-LEARN</span><span>FITTED PIPELINE</span><span>MODAL INFERENCE</span></div></div></section>
 <section className="workspace"><form className="panel input-panel" onSubmit={submit}><div className="panel-heading"><div><small>01 / INPUT PARAMETERS</small><h2>Player profile</h2></div><span className="chip">6 FEATURES</span></div><div className="form-grid">{fields.map((f,i)=><label key={f.key}><div className="field-title"><span><b>0{i+1}</b>{f.label}</span><small>{f.unit}</small></div>{f.key==='Previous_Injuries'?<select value={values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.value})}><option value="0">0 — No prior injury</option><option value="1">1 — Prior injury</option></select>:<input required type="number" min={f.min} max={f.max} step={f.step} placeholder={String(f.value)} value={values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>}<span className="help">{f.description}</span><span className="range">{f.key} · {f.min}–{f.max}</span></label>)}</div><div className="form-footer"><span>↳ Inputs processed by the deployed model</span><button disabled={busy} type="submit">{busy?<><i className="spinner"/> ANALYZING…</>:<>RUN PREDICTION <span>↗</span></>}</button></div></form>
 <aside className="panel result-panel"><div className="panel-heading"><div><small>02 / MODEL OUTPUT</small><h2>Analysis console</h2></div><span className="cross">+</span></div><div role="status" aria-live="polite" className={'output '+(result?'revealed':'')}>{busy?<><div className="scan"/><h3>Running fitted pipeline</h3><p>Waiting for live Modal inference…</p></>:result?<><span className="eyebrow">PREDICTED INJURY CLASS</span><h3 className="result-label">{result.label}</h3><div className="gauge" style={{'--progress':percent+'%'}}><div><strong>{percent.toFixed(1)}<small>%</small></strong><span>CLASS 1 PROBABILITY</span></div></div><div className="class-row"><span>MODEL CLASS</span><b>{result.prediction}</b></div><p>Probability is the model’s estimate for label 1, not a clinically validated injury risk.</p></>:<><div className="idle-symbol">⌖</div><h3>Awaiting player profile</h3><p>Enter six feature values and run the model to see its actual prediction here.</p><span className="terminal">&gt; inference.ready_</span></>}</div>{error&&<div className="error" role="alert">{error}</div>}<div className="system-details"><div><span>MODEL</span><b>Logistic regression</b></div><div><span>PIPELINE</span><b>{status==='online'?'Fitted · ready':'Awaiting connection'}</b></div><div><span>COMPUTE</span><b>Modal / FastAPI</b></div></div></aside></section>
 <section className="telemetry"><div><small>DATASET RECORDS</small><strong>{metadata?.rows??'—'}<span>player observations</span></strong></div><div><small>HOLDOUT ACCURACY</small><strong>{metadata?`${(metadata.metrics.accuracy*100).toFixed(1)}%`:'—'}<span>unseen test data</span></strong></div><div><small>HOLDOUT ROC-AUC</small><strong>{metadata?metadata.metrics.roc_auc.toFixed(3):'—'}<span>0.5 = chance ranking</span></strong></div><div><small>MODEL VERSION</small><strong>{metadata?.sklearn_version??'—'}<span>scikit-learn</span></strong></div></section><div className="research-note"><span>ⓘ</span><p><b>Research context.</b> This dataset has limited predictive signal. The app demonstrates real model inference; it is not validated for player safety decisions. *Age, kg, and cm are inferred conventions, not documented units. Recovery must be known before the predicted outcome to avoid leakage.</p></div></main><footer><span>INJURY PREDICT <i>/</i> APPLIED MACHINE LEARNING</span>{API?<a href={API+'/docs'} target="_blank" rel="noreferrer">EXPLORE API DOCS ↗</a>:<span>API CONNECTION NOT CONFIGURED</span>}</footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
